<!DOCTYPE html>
<html lang="en">
<head>
    <title>
leave &quot;if err != nil&quot; alone? &#xB7; Issue #32825 &#xB7; golang/go &#xB7; GitHub -
linksfor.dev(s)
    </title>
    <link rel="alternate" type="application/rss+xml" title="Linksfor.dev(s) feed" href="https://linksfor.dev/feed.rss" />
    <meta charset="utf-8">
    <meta name="Description" content="A curated source of links that devs might find interesting. Updated around the clock." />
    <meta name="google" value="notranslate">
    <link rel="stylesheet" type="text/css" href="/style.css" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
</head>
<body>
    <div class="grid">
        
<div class="readable">
    <div id="readOverlay" class="style-ebook"><div id="readInner" class="margin-medium size-medium"><h1>leave "if err != nil" alone? · Issue #32825 · golang/go · GitHub</h1><div><div id="" class="d-block comment-body markdown-body  js-comment-body"><p>It might not make sense to change it, because the wrong problem is trying to be solved.</p><p>The code that we are familiar with is not error handling.</p><div class="highlight highlight-source-go"><pre><span class="pl-k">if</span> err != <span class="pl-c1">nil</span> {
  <span class="pl-k">return</span> err
}</pre></div><p>This is error <code>nil</code> handling. At no point in this pattern is the value of an error handled.</p><p>If I were to demonstrate this in a different language, Ruby.</p><div class="highlight highlight-source-ruby"><pre><span class="pl-k">begin</span>
 some_method_that_raises_an_error
<span class="pl-k">rescue</span> =&gt; e <span class="pl-c"><span class="pl-c">#</span> catch any exception</span><span class="pl-k">retry</span> e        <span class="pl-c"><span class="pl-c">#</span> throw it up again</span><span class="pl-k">end</span></pre></div><p>This relays the same behavior as the golang code. When we detect that an exception occurred and then reraise it. We just throw it up the stack.</p><p>In golang, we <code>return</code> it.</p><p>Where is the actual <em>error handling</em> occurring?</p><p>We've all had similar experiences of the failure of this pattern. For example, receiving a <code>file not found</code> error and then spending a large length of time tracing the original <em>thrower</em> of this error.</p><p>This is why I believe the <code>try</code> proposal (and others) are faulting. We don't have a good pattern for actually handling errors.</p><p>I've see <code>err.Error()</code> string checking, type assertions, etc. to actually inspect the error.<br>We need a pattern for this inconsistency. It feels like <code>xerrs</code> might be solving this, but it also doesn't feel complete yet.</p></div></div></div></div>
</div>
    </div>
    <footer>
        <div>created by buildstarted &copy; 2020 <a href="/about">about</a></div>
        <div>Share this page on social media: copy and paste this url https://linksfor.dev/</div>
        <div>If you prefer RSS: <a href="https://linksfor.dev/feed.xml">https://linksfor.dev/feed.xml</a></div>
    </footer>
    
    <script>
        (function () {
            var COLLECT_URL = "https://dna.buildstarted.com/t";
            var SITE_ID = "linksfor.devs";
            var GLOBAL_VAR_NAME = "__DNA__";

            window[GLOBAL_VAR_NAME] = {};

            window[GLOBAL_VAR_NAME].sendPageView = function () {
                var path = location.pathname;
                var referrer = document.referrer;

                var url = COLLECT_URL + "?siteid=" + SITE_ID + "&p=" + encodeURIComponent(path) + "&r=" + encodeURIComponent(referrer);

                try { fetch(url, { method: "GET" }); } catch (e) { }
            };

            window[GLOBAL_VAR_NAME].sendPageView();
        })();
    </script>
</body>
</html>