<!DOCTYPE html>
<html lang="en">
<head>
    <title>
c&#x2B;&#x2B; - What happens if &#x27;throw&#x27; fails to allocate memory for exception object? -
linksfor.dev(s)
    </title>
    <link rel="alternate" type="application/rss+xml" title="Linksfor.dev(s) feed" href="https://linksfor.dev/feed.rss" />
    <meta charset="utf-8">
    <meta name="Description" content="A curated source of links that devs might find interesting. Updated around the clock." />
    <meta name="google" value="notranslate">
    <link rel="stylesheet" type="text/css" href="/style.css" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
</head>
<body>
    <div class="grid">
        
<div class="readable">
    <div id="readOverlay" class="style-ebook"><div id="readInner" class="margin-medium size-medium"><h1>c++ - What happens if 'throw' fails to allocate memory for exception object?</h1><div><div class="post-text" itemprop="text"><p><em>(providing my own answer... I'll wait for few days and if there are no problems with it -- I'll mark it as accepted)</em></p><p>I spent some time investigating this and here is what I unearthed:</p><ul><li>C++ standard does not specify what is going to happen in this case</li><li>Clang and GCC seem to use <a href="https://itanium-cxx-abi.github.io/cxx-abi/abi-eh.html" rel="noreferrer">C++ Itanium ABI</a></li></ul><p>Itanimum ABI suggests to use heap for exceptions:</p><blockquote><p>Storage is needed for exceptions being thrown. This storage must
  persist while stack is being unwound, since it will be used by the
  handler, and must be thread-safe. Exception object storage will
  therefore normally be allocated in the heap</p><p>...</p><p>Memory will be allocated by the <code>__cxa_allocate_exception</code> runtime library routine.</p></blockquote><p>So, yeah... throwing an exception will likely involve locking mutexes and searching for a free memory block. :-(</p><p>It also mentions this:</p><blockquote><p>If __cxa_allocate_exception cannot allocate an exception object under these constraints, it calls terminate()</p></blockquote><p>Yep... in GCC and Clang "throw myX();" can kill your app and you can't do a thing about it (maybe writing your own <code>__cxa_allocate_exception</code> can help -- but it certainly won't be portable)</p><p>It gets even better:</p><blockquote><p>3.4.1 Allocating the Exception Object</p><p>Memory for an exception object will be allocated by the
  __cxa_allocate_exception runtime library routine, with general requirements as described in Section 2.4.2. If normal allocation
  fails, then it will attempt to allocate one of the emergency buffers,
  described in Section 3.3.1, under the following constraints:</p><ul><li>The exception object size, including headers, is under 1KB. </li><li>The current thread does not already hold four buffers.</li><li>There are fewer than 16 other threads holding buffers, or <strong>this thread
  will wait until one of the others releases its buffers</strong> before acquiring one.</li></ul></blockquote><p>Yep, your program can simply hang! Granted chance of this are small -- you'd need to exhaust memory and your threads need to use up all 16 emergency buffers and enter wait for another thread that should generate an exception. But if you do things with <code>std::current_exception</code> (like chaining exception and passing them between threads) -- it is not so improbable.</p><p><strong>Conclusion:</strong></p><p>This is a deficiency in C++ standard -- you can't write 100% reliable programs (that use exceptions). Text book example is a server that accepts connections from clients and executes submitted tasks. Obvious approach to handle problems would be to throw an exception, which will unwind everything and close connection -- all other clients won't be affected and server will continue to operate (even under low memory conditions). Alas, such server is impossible to write in C++.</p><p>You can claim that modern systems (i.e. Linux) will kill such server before we reach this situation anyway. But (1) it is not an argument; (2) memory manager can be set to overcommit; (3) OOM killer won't be triggered for 32-bit app running on 64bit hardware with enough memory (or if app artificially limited memory allocation).</p><p>On personal note I am quite pissed about this discovery -- for many years I claimed that my code handles out-of-memory gracefully. Turns out I lied to my clients. :-( Might as well start intercepting memory allocation, call <code>std::terminate</code> and treat all related functions as <code>noexcept</code> -- this will certainly make my life easier (coding-wise). No wonder they still use Ada to programs rockets.</p></div></div></div></div>
</div>
    </div>
    <footer>
        <div>created by buildstarted &copy; 2020 <a href="/about">about</a></div>
        <div>Share this page on social media: copy and paste this url https://linksfor.dev/</div>
        <div>If you prefer RSS: <a href="https://linksfor.dev/feed.xml">https://linksfor.dev/feed.xml</a></div>
    </footer>
    
    <script>
        (function () {
            var COLLECT_URL = "https://dna.buildstarted.com/t";
            var SITE_ID = "linksfor.devs";
            var GLOBAL_VAR_NAME = "__DNA__";

            window[GLOBAL_VAR_NAME] = {};

            window[GLOBAL_VAR_NAME].sendPageView = function () {
                var path = location.pathname;
                var referrer = document.referrer;

                var url = COLLECT_URL + "?siteid=" + SITE_ID + "&p=" + encodeURIComponent(path) + "&r=" + encodeURIComponent(referrer);

                try { fetch(url, { method: "GET" }); } catch (e) { }
            };

            window[GLOBAL_VAR_NAME].sendPageView();
        })();
    </script>
</body>
</html>